config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'

	post 'create_users' => 'welcome#create_users'
  get 'users' =>'welcome#users'
  get 'show_user' => 'welcome#show_user'
  get 'products' => 'welcome#products'
  get 'products_index' => 'welcome#products'
  post 'products' =>'welcome#create_products'
  get 'show_product' => 'welcome#show_product'
  get 'edit' => 'welcome#edit_user'
  post 'update_user' => 'welcome#update_user'
  get 'edit_product' => 'welcome#edit_product'
 	patch 'product' =>'welcome#update_product'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@product = Product.new
  end

  def create_users
  	user = User.create(name: params[:name], age: params[:age].to_i)
  	redirect_to users_path
  end	



  def users
  	@users = User.all

  end


  def show_user
    @user = User.find(params[:id])
  end  

  def edit_user
    @user = User.find(params[:id])
  end  

  def update_user
    user = User.find(params[:id])
    user.update(name: params[:name], age: params[:age])
    redirect_to show_user_path(id: params[:id])
  end 



  def show_product
    @product = Product.find(params[:id])
  end  


  def create_products
  	product = Product.create(product_params)
  	redirect_to products_path
  end	


  def products
  	@products = Product.all
  end

  def edit_product
    @product = Product.find(params[:id])
  end  
  
  def update_product
    # @product = Product.find(params[:id])
    @product = Product.find(params["product"][:id])
    @product.update(product_params)
    
    redirect_to show_product_path(id: @product.id)
  end 


  private

  	def product_params
  		params.require(:product).permit(:name, :price, :quantity)
  	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fall17NoScaffolds</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/edit_product.html.erb
<h3>Edit product </h3>

	<%= form_for(@product, url: product_path, method: :patch ) do |f| %>
		<%= f.hidden_field :id, value: @product.id %>
	 	<%= f.text_field :name, value: @product.name %>
	 	<%= f.number_field :price, value: @product.price %>
	 	<%= f.number_field :quantity, value: @product.quantity %>
 	<%= f.submit "Edit Product" %>
 	<% end %>

app/views/welcome/edit_user.html.erb
<h3>Edit user <%= @user.name %></h3>
<%= form_tag update_user_path do %>
	<%= text_field_tag :name, @user.name %>
	<%= number_field_tag :age, @user.age %>
	<%= hidden_field_tag :id, @user.id %>
	<%= submit_tag "Edit User" %>	
<% end %>

app/views/welcome/index.html.erb
<h1>Home Page</h1>

<h3>Let's create a new user</h3>
<%= form_tag create_users_path do %>
	<%= text_field_tag :name, nil, placeholder: "Enter Your Name" %>
	<%= number_field_tag :age, nil, placeholder: "Enter Your Age" %>
	<%= submit_tag "Create New User" %>	
<% end %>


<h3>Let's create a new product </h3>
 <%= form_for @product do |f|%>
 	<%= f.text_field :name, placeholder: "Enter Product Name" %>
 	<%= f.number_field :price, placeholder: "Enter price", step: :any %>
 	<%= f.number_field :quantity, placeholder: "Enter quantity" %>
 	<%= f.submit "Create Product" %>
 	<% end %>

<%= link_to "User Index", users_path %>  |  
<%= link_to "Product Index", products_path %>

app/views/welcome/products.html.erb
<h1>All the Products</h1>

<table border="2">
    <tr>
        <th>Name</th>
				<th>Price</th>
        <th>Quantity</th>
    </tr>

    <% @products.each do |product| %>
        <tr>
            <td><%= link_to product.name, show_product_path(id: product.id) %></td>
            <td><%= number_to_currency product.price %></td>
	    	<td><%= product.quantity %></td>
	</tr>
    <% end %>
</table>

<p>
<%= link_to "Return to Index", root_path %>
</p>

app/views/welcome/show_product.html.erb
<h1>Product: <%= @product.name %> </h1>
<h2>Price: <%=@product.price %></h2>
<h2>Quantity: <%=@product.quantity %></h2>

<%= link_to "Product Index", products_path %>
<%= link_to "Edit Product", edit_product_path(id: @product.id) %>

app/views/welcome/show_user.html.erb
<h1>User: <%= @user.name %> </h1>
<h2>Age: <%=@user.age %></h2>

<%= link_to "User Index", users_path %>  |  
<%= link_to "Edit User", edit_path(id: @user.id) %>

app/views/welcome/users.html.erb
<h1>Here are all of our users:</h1>

<table style="border:2px">
	<tr>
		<th>Name</th>
		<th>Age</th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= link_to user.name, show_user_path(id: user.id) %></td>
		<td><%= user.age %></td>
	</tr>

<% end%>


</table>

<%= link_to "Return to Index", root_path %>